name: Creative Approaches blog by Jai
description: >
    A simple blog for completing homework for Creative Approaches to Emerging Technologies class at Olin.

master_repo: false
url: "http://jpatil6.github.io/creativeapproaches2"
baseurl: "/creativeapproaches2"

markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           Creative Approaches blog by Jai
  avatar:         ""
  email:          "jpatil@olin.edu"
  # Social networking links used in footer. Update and remove as you like.
  github: https://github.com/jpatil6
  
# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
